/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Text.geometry} material={materials.Material} position={[0, 0.05, 0.25]} rotation={[11, 0, 0]} scale={3} />
    </group>
  )
}

useGLTF.preload('/model.gltf')